= Introduction

[quote,  President John F. Kennedy,  Address at Rice University on the Nation's Space Effort, 1962]
"We choose to [do these] things, not because they are easy, but because they are hard."

Welcome, cadet!

This book is designed to take you from 0-60 with the Micronaut framework, helping you get productive quickly, acclimated to best practices, while also giving you a grounding in the foundational principles that drive the framework and make it truly unique among its peers.

With that in mind, this introduction is going to be a bit different than you might find in many tech books: we're going to hit the ground running by creating and bootstrapping a production-ready Micronaut app, including full code listings, and deploy it to the cloud. Along the way, we'll discuss what Micronaut has to offer to developers and organizations in today's cloud-native, highly-distributed environment.

In later chapters, we will explore the features of the framework in much more detail, including testing, database access, streaming applications, using Micronaut with modern Single-Page Application UIs, and more.

Note that if you prefer, it's perfectly acceptable to simply read along with this introductory section (all the code and relevant outputs will be listed here in the text),

== Entry Exam

Before we start, we will briefly list out the requirements that you'll want to have under your belt to get the most from this introduction (and the rest of the book):

- Familiarity with Java, or a similar C-family programming language.
- A properly configured Java Development Kit (JDK), version 8 or above.

Believe it or not, that's really about it! If you have experience with frameworks like Spring Boot, Grails, or Quarkus, you'll find that useful, but we won't presume any of that in this book.

== Readying the Launchpad

To create your Micronaut app, the best place to start is the official Micronaut Launch website: https://micronaut.io/launch/[https://micronaut.io/launch]. This generator supports the creation of multiple types of applications, including Command Line Interface (CLI) apps, serverless functions (which we'll discuss in Chapter _), and more.

[source]
----
Screenshot: Micronaut Launch
----

Let's get started by creating our first Micronaut app using the Launch website.

=== Create/Download the project

Browse to https://micronaut.io/launch/. Feel free to play around with some of the options, but this introduction, we will be using all the defaults (listed below for your reference), so be sure to refresh the page when you're ready to download your new project.

- Application Type: Micronaut Application
- Java Version: 11 (feel free to adjust this to match the JDK you want to use)
- Base Package: `com.example`
- Name: `demo`
- Micronaut Version: Latest stable release (2.5.1 at the time of writing)
- Language: Java
- Build: Gradle
- Test Framework: JUnit

No additional features should be selected for this first project - no worries, we will get to play with many of them in future chapters!

Before we download the project, click the "Preview" button to load the configured project in an embedded browser. This feature of Launch allows you to experiment with different combinations of settings/features and see in advance what the resulting project would look like.

[source]
----
Screenshot: Micronaut Launch (Preview)
----

Once you've had a look around, dismiss the Preview window, and click the "Generate" button to download a ZIP file of your shiny new Micronaut project!

=== Setting up a development environment

We've chosen Gradle as our build tool for this project. Micronaut Launch can also generate Maven builds, and we'll use both tools in this book, but even if you're not familiar with Gradle, you won't have any trouble with this introduction. The downloaded project includes a "wrapper" script (`gradlew` for Unix systems, `gradlew.bat` for Windows) that will take care of downloading and installing the correct Gradle version for you.

Because it uses standard build tools like Gradle and Maven, Micronaut doesn't require any particular IDE or plugins. For now, any IDE or text editor you are comfortable with will do - ideally one that provides good syntax highlighting for Java. We'll VSCode in the screenshots for this book.

Unzip your project into a convenient directory, and open a terminal session (or command prompt in Windows) and navigate into the expanded project directory.

Run the following command to verify your JDK is configured correctly:

[source,bash]
----
~ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.10)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.10, mixed mode, sharing)
----

If you don't get similar output (or if your Java version is older than 8), you may either consult the internet for guidance on installing the correct version of the JDK on your operating system, or check out the SDKMan package manager (https://sdkman.io/) and use it to install and switch between multiple JDK versions (as well as many other useful Java-based tools and frameworks, including Micronaut).

If your JDK installation checks out, it's time to fire up the engines on our new Micronaut project! Run the following command:

[source,bash]
----
~ ./gradlew run
----

If you're running on Windows, simply leave off the `./` before the name of the script.

[source,bash]
----
~ gradlew run
----

If all goes well, you should see some output like below:

[source,bash]
----
> Task :run
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.1)

20:49:37.191 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 571ms. Server Running: http://localhost:8080
----

Congratulations! Your first Micronaut application is primed and ready for launch!

=== Creating your first controller

At this point if you were to check out http://localhost:8080, you might be disappointed - it's not the most clever 404 page on the internet.

[source]
----
{"message":"Page Not Found","_links":{"self":{"href":"/","templated":false}}}
----

Let's fix this by writing some code to return an obligatory greeting when we hit this URL.

From within the expanded project directory, change to the subdirectory `src/main/java/com/example`, and create a new file named `HomeController.java`. If you're using an IDE, you can use the IDE's project browser to navigate to this directory and create the file.

Add the following code to this new file:

[source,java]
----
package com.example;

import io.micronaut.http.*;

@Controller
public class HomeController {

    @Get(value = "/{name}", produces = MediaType.TEXT_PLAIN)
    public String hello(String name) {
        return "Hello " + name + "!";
    }
}
----

Depending on your familiarity with Java and MVC frameworks like Spring and Grails, this code might be extremely intuitive, or not. We'll dive deeply into controllers in Micronaut and the HTTP server capabilities of the framework later, but for now it's sufficient to understand that a controller is a piece of code that handles HTTP requests (like from our web browser).  One kind of HTTP request is the "GET" request (which is what happens when we load a URL in our browser), and in this code we are telling Micronaut to return a plain text string to "GET" requests to our application.

This style of controller (or resource, in RESTspeak) is a well-established artifact in modern Java web frameworks. So what makes Micronaut controllers so special? The answer lies in what you _don't_ see in this code listing.

=== Framework Magic

Most Java developers don't really want to be writing code to create and receive HTTP requests, parse JSON, manually wire together dependent classes (or beans), create and manage database transactions, Of course, even in open source software,or any of the various boilerplate tasks that almost every application requires. For that reason, frameworks like Spring and libraries like Jackson exist to provide these features for "free", relying on various methods like code-generation, runtime reflection (inspecting your code at runtime and inserting additional behavior), and generating proxy classes that stand in "front" of your code and wrap it with additional functionality provided by the framework.

As the saying goes, however, nothing is truly "free", and this applies to Java application frameworks as well.

Take a look at our controller from above.

[source,java]
----
@Controller
public class HomeController {

    @Get(value = "/{name}", produces = MediaType.TEXT_PLAIN)
    public String hello(String name) {
        return "Hello " + name + "!";
    }
}
----

While this is a trivial example, there is nonetheless a fair bit of complexity involved in actually creating a functioning HTTP endpoint like this. We need an HTTP server to accept requests, and we need to route the request to the correct method, extract the URL component/s and map them to arguments of the method, create the proper HTTP headers, and finally return the response. We also probably want this controller class to be instantiated for us when the application starts up, and we'd like it to be wired into a Dependency Injection container (more on this in a moment!), so that we can inject other beans into it (for example, a JDBC repository class, or a logging service).

Any good Java framework will help you with these requirements, however, most will do this by _dynamically inspecting your code at runtime_ (either during the application startup, or "lazily" when a given class or method is invoked). Most often this involves a process called *reflection*, as mentioned above, wherein the framework will "crawl" your controller class (as well as any other application classes) and inspect each method and class member, usually *caching metadata about them as well and storing it in memory* (to speed up lookups later on).

In short, reflection-based frameworks - including Spring - rely on a fairly expensive process to analyze and cache information about your code at runtime, which is then used to provide the framework's features to your application. It's a tradeoff which most developers are glad to make, in return for an expressive and productive programming model.

=== The Problem with Reflection

[image]
----
[Reflection]
----

The metadata gathered via reflection in a typical Spring application is surprisingly expansive. As mentioned above, every method and class member is inspected and cached, however, these caches are typically not shared between __, which means that the amount of memory consumed by these caches can be multiplied very easily. Even more problematic, the memory usage and runtime cost to reflection-based frameworks is tightly correlated to the size and complexity of the application code base - the more classes, methods, and inter-dependencies within the application, the more memory and time will be required in order for the framework to do its job.

In a traditional monolithic Java application, these costs are usually easy to justify in return for the greater productivity and developer happiness offered by a well-designed framework. If you're running a single server and only restarting the app for the occasional release, throwing gigabytes of RAM and additional minutes of waiting for startup might be a reasonable compromise. However, in the era of microservices, serverless, cloud computing and PaaS providers, the calculus changes dramatically.

=== The Micro Factor

In a microservice architecture, it is not uncommon to have dozens or even hundreds of individual applications (or services) deployed in a cloud infrastructure. The runtime analysis and memory costs that were tolerable for a single monolith begin to scale up dramatically as the architecture grows and evolves, and given the lack of any practical mechanism to share reflective caches across JVM processes, organizations are faced with the unpleasant prospect of paying for (in some cases) the exact same metadata being collected and stored in memory for every service.

The problem is exacerbated when we consider serverless applications (or "functions") using reflection-based frameworks. Most serverless platforms minimize costs by only launching the application when requests are received, and shutting it down after a set period of inactivity. This means that rapid time to first request is extremely valuable, for reasons of both performance and cost. For a serverless function to spend precious cycles during startup to inspect and generate the _same_ metadata repeatedly, is a non-starter (we cannot confirm or deny whether a pun may have been intended).

The bottom line is that in a cloud-native system, the memory and startup time penalties incurred by reflection-based frameworks comprise a *direct, quantifiable cost* to organizations and projects. For this reason, many developers have concluded that JVM frameworks, despite their expressive and powerful programming model, are simply ill-suited for microservices and serverless applications, turning to alternate platforms like Go or Node.js.

=== The JVM Strikes Back

It's often said that the strength of Java is its ecosystem, and it's certainly the case that, for many organizations, walking away from the JVM as a platform is simply not a viable or desirable option.  Fortunately, the demands of cloud-native architecture are being met by exciting innovations, including GraalVM, an alternate JVM that creates "native images" which can run nearly as fast as an OS-native executable program, as well as a move away from reflection and towards compile-time analysis, aka *Ahead-Of-Time Compilation*.

Micronaut applies the AOT approach to the problem of creating expressive, productive frameworks without relying on expensive and inefficient reflection. The genius of Micronaut is that, rather than do away with powerful features like DI, Aspect-Oriented Programming (AOP), transaction-management, etc, these features are implemented using *compile-time analysis of your code*.

This means that the memory and analysis costs that you would otherwise incur at runtime _every time your app is launched_, are now paid only once, when the application is compiled. Once compiled, the metadata required by the framework, as well as any generated framework code, are baked into the bytecode of your deployable artifact (WAR or JAR file), requiring little to no runtime inspection when the application is launched.  What's more, as your app's codebase grows in size and/or complexity, there is no longer a linear correlation between code growth and memory/startup time cost - any additional cost simply happens when the app is compiled, while the runtime cost remains essentially fixed (and very low).

[source,java]
----
@Controller
public class HomeController {

    @Get(value = "/{name}", produces = MediaType.TEXT_PLAIN)
    public String hello(String name) {
        return "Hello " + name + "!";
    }
}
----
